Repository hybridapp-io/ham-resource-discoverer, pull requests merged in 2020-05, with the labels that each got.

#2 upgrade to operator sdk 0.17.0
  common/scripts/install-operator-sdk.sh
  go.mod
  go.sum
Labels: approved, lgtm, size/L

#3 patchObject does not change ownership
  pkg/controller/deployable/deployable_utils.go
Labels: approved, lgtm, size/M

#4 additional logging and error handling
  pkg/apis/core/v1alpha1/deployer_types.go
  pkg/controller/application/application_controller.go
  pkg/controller/application/application_controller_test.go
  pkg/controller/deployable/deployable_utils.go
Labels: approved, lgtm, size/M

#5 Update Dockerfile
  build/Dockerfile
Labels: approved, lgtm, size/XS

#6 fix readme and potential port conflict
  OWNERS
  README.md
  cmd/operator/manager.go
Labels: approved, lgtm, size/S

#7 Update Dockerfile
  build/Dockerfile
Labels: approved, lgtm, size/XS

#8 resource discovery reconciliation
  pkg/apis/core/v1alpha1/deployer_types.go
  pkg/controller/application/application_controller.go
  pkg/controller/application/application_controller_test.go
  pkg/controller/deployable/deployable_controller.go
  pkg/controller/deployable/deployable_controller_test.go
  pkg/controller/deployable/deployable_utils.go
Labels: approved, lgtm, size/XL

#9 use annotation defined in ham-deployable-operator
  go.mod
  go.sum
  pkg/apis/core/v1alpha1/deployer_types.go
  pkg/controller/application/application_controller.go
  pkg/controller/application/application_controller_test.go
  pkg/controller/deployable/deployable_controller.go
  pkg/controller/deployable/deployable_controller_test.go
  pkg/controller/deployable/deployable_utils.go
Labels: approved, lgtm, size/M

#10 updated dependency version
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#11 Additional logging
  pkg/controller/application/application_controller.go
  pkg/controller/application/application_controller_test.go
  pkg/controller/deployable/deployable_controller.go
  pkg/controller/deployable/deployable_controller_test.go
  pkg/controller/deployable/deployable_suite_test.go
  pkg/controller/deployable/deployable_utils.go
Labels: approved, lgtm, size/L

#12 namespaced informer factory
  pkg/controller/deployable/deployable_controller.go
Labels: approved, lgtm, size/XS
