Repository hybridapp-io/ham-resource-discoverer, pull requests merged in 2020-07, with the labels that each got.

#21 update addMetrics and serveCRMetrics
  cmd/operator/manager.go
  go.sum
Labels: approved, lgtm, size/M

#22 Scope
  deploy/crds/core.hybridapp.io_deployers_crd.yaml
  go.mod
  hack/test/core.hybridapp.io_deployersets_crd.yaml
  pkg/apis/core/v1alpha1/deployer_types.go
  pkg/controller/deployer/deployer_controller_test.go
Labels: approved, lgtm, size/XL

#23 Refreshed owners list
  OWNERS
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#24 Release 0.0.1
  Makefile
Labels: approved, lgtm, size/XS
