Repository hybridapp-io/ham-resource-discoverer, pull requests merged in 2020-06, with the labels that each got.

#14 remove bou.ke/monkey dependency
  go.mod
  go.sum
Labels: approved, lgtm, size/S

#16 No duplicate RHACM deployables from app discovery
  pkg/controller/application/application_controller_test.go
  pkg/controller/application/application_suite_test.go
  pkg/controller/application/generic_controller.go
  pkg/controller/deployable/deployable_controller_test.go
  pkg/controller/deployable/deployable_suite_test.go
  pkg/controller/deployable/deployable_utils.go
Labels: approved, lgtm, size/L

#17 additional unit tests
  pkg/controller/application/application_controller_test.go
  pkg/controller/deployable/deployable_controller_test.go
Labels: approved, lgtm, size/M

#18 Use RHACM deployable GVR on hub
  pkg/controller/deployable/deployable_utils.go
Labels: approved, lgtm, size/XS

#19 strengthen the source_object annotation
  pkg/controller/deployable/deployable_utils.go
Labels: approved, lgtm, size/XS
